### ISSUE TITLE
Calling `hide` on a background which isn't already shown freezes game

### ISSUE THREAD

**Issue by seleb** [lunafromthemoon/RenJS-V2#29]
Example:

```yaml
start:
  - hide mybg:
  - text: this text wont be reached
```

This freezes the game, but should probably be silently ignored (or log a warning at most).
