### ISSUE TITLE
Markup on the first line of a rolling credits effect renders the markup itself 

### ISSUE THREAD

**Issue by seleb** [lunafromthemoon/RenJS-V2#31]
Example:
```yaml
start:
  - effect ROLLINGCREDITS:
    text:
      - test
  - effect ROLLINGCREDITS:
    text:
      - (bold)text(end)
```

The first example here will render `test` as a credits roll as expected, but the second will render `(bold)text(end)` instead of `text` in bolded letters.
