### ISSUE TITLE
Choices without body text will cause errors

### ISSUE THREAD

**Issue by seleb** [lunafromthemoon/RenJS-V2#33]
Example:

```yaml
start:
  - choice:
    - "a":
      - text: "a response"
    - "b":
      - text: "b response"
    - "c":
      # no response for c
  - text: generic response
```

Having a choice like this can be useful for pacing/"illusion-of-choice" style choices that don't actually do anything specific, but currently they will error out if selected.

Known workaround: You can put something unnecessary like a variable declaration in the choice body so that it doesn't error out, and continues to the rest of the scene, e.g.
```yaml
start:
  - choice:
    - "fake choice":
      - var null: null
  - text: generic response
```
