### ISSUE TITLE
Can't move cg between layers

### ISSUE THREAD

**Issue by seleb** [lunafromthemoon/RenJS-V2#35]
I couldn't figure out any way to seamlessly move a cg from being behind characters to in front, or vice versa. You can fade and re-show the same cg on separate lines of the script, but it may cause a flicker due to hide being async (even with `CUT`). 

Example:
```yaml
start:
  - show mycharacter: look
  - show mycg: WITH CUT BEHIND
  - hide mycg: WITH CUT
  - show mycg: WITH CUT
```

A possible solution would be to allow a `show` call on a cg which is already onscreen to move the existing sprite (currently it seems to do nothing).

Example:
```yaml
start:
  - show mycharacter: look
  - show mycg: WITH CUT BEHIND
  - show mycg: WITH CUT
```
